server:
  port: 8081
  context-path:  /


spring:
  redis:
    host:
    port: 6379
#    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8